server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 1
    password:
    listen-pattern: __keyevent@1__:expired

mall:
  security:
    token-expired-time: 86400000
    secret-key: ThisIsASecretKeyForMall
  order:
    max-sku-limit: 9999
    pay-time-limit: 60
    year-codes: A,B,C,D,E,F,G,H,I